version: "2"
services:
  web:
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`mk.victorberland.com`)"
      - "traefik.http.routers.jenkins.tls.certresolver=mytlschallenge"

    networks:
      - web

networks:
  web:
    external: true
