version: "2"
services:
  web:
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=mytlschallenge"

    networks:
      - web

networks:
  web:
    external: true
